import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { buildSmokeData, nativeVersions, sha256 } from '../../scripts/port-smoke-data.mjs';
import { loadPortMappings, neovimHighlights } from '../../scripts/ports.mjs';
import { ansiSlots, portableColor, portableVariants, renderAnsi } from '../../scripts/portable.mjs';
import { compileSources, loadSources } from '../../scripts/tokens.mjs';

test('native smoke expectations identify exact current generated bytes and resolved renderers', () => {
  const runId = '22222222222242228222222222222222';
  const models = compileSources(loadSources());
  const mappings = loadPortMappings();
  for (const version of nativeVersions) {
    const data = buildSmokeData({ version, runId });
    assert.equal(data.runId, runId);
    assert.equal(data.version, version);
    assert.equal(data.schemaVersion, 1);
    assert.equal(data.themes.length, 3);
    data.themes.forEach((theme, index) => {
      const model = models.find(item => item.variant.key === portableVariants[index]);
      assert.equal(theme.id, model.variant.id);
      assert.equal(theme.sha256, sha256(readFileSync(theme.path)));
      assert.deepEqual(theme.highlights, neovimHighlights(mappings.neovim, model));
      const terminal = renderAnsi(mappings.ansi, model);
      assert.deepEqual(theme.terminal, ansiSlots.map(slot => terminal[slot]));
      assert.equal(theme.intents.property, portableColor('{semantic.syntax.property}', model));
      assert.equal(theme.intents.variable, portableColor('{semantic.syntax.variable}', model));
      assert.notEqual(theme.intents.property, theme.intents.variable);
      assert.equal(theme.intents.regexp, portableColor('{semantic.syntax.regexp}', model));
      assert.equal(theme.intents.comment, portableColor('{semantic.syntax.comment}', model));
      assert.equal(theme.intents.constant, portableColor('{semantic.syntax.constant}', model));
    });
  }
});

test('native smoke rejects unpinned versions and invalid run identities', () => {
  for (const version of ['0.11.3', '0.12.4', 'nightly', undefined]) {
    assert.throws(() => buildSmokeData({ version }), /Unsupported pinned Neovim version/);
  }
  for (const runId of ['', '../other-run', 'not-a-guid', '-'.repeat(32)]) {
    assert.throws(() => buildSmokeData({ version: '0.11.4', runId }), /GUID runId/);
  }
});
