import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { aliasTarget, compileSources, loadSources, root, stableJson, validateSchema } from './tokens.mjs';
import { ansiSlots, portableColor, portableVariants, renderAnsi } from './portable.mjs';
import { renderOhMyPosh } from './oh-my-posh.mjs';

export function loadPortMappings() {
  return Object.fromEntries(['ansi', 'windows-terminal', 'neovim', 'oh-my-posh'].map(name => [
    name, JSON.parse(readFileSync(resolve(root, 'adapters', `${name}.json`), 'utf8'))
  ]));
}

export function renderWindowsTerminal(mapping, ansi, model) {
  validateSchema('windows-terminal-mapping', mapping);
  const nativeSlot = slot => slot.replace('magenta', 'purple').replace('Magenta', 'Purple');
  const theme = {
    name: model.variant.label,
    ...Object.fromEntries(Object.entries(mapping).map(([key, value]) => [key, portableColor(value, model)])),
    ...Object.fromEntries(Object.entries(renderAnsi(ansi, model)).map(([key, value]) => [nativeSlot(key), value]))
  };
  validateSchema('windows-terminal-theme', theme);
  return theme;
}

export function neovimHighlights(mapping, model) {
  validateSchema('neovim-mapping', mapping);
  const groups = mapping.highlights;
  for (const name of ['Normal', 'Comment', 'String', 'Function', '@variable.member', '@string.regexp', '@markup.heading', '@lsp.type.variable']) {
    if (!Object.hasOwn(groups, name)) throw new Error(`Missing required Neovim highlight: ${name}`);
  }
  for (const name of Object.keys(groups)) {
    for (const key of ['fg', 'bg', 'sp']) {
      const expression = groups[name][key];
      if (!expression) continue;
      const roles = typeof expression === 'string' ? [expression] : expression.over;
      if (roles.some(role => aliasTarget(role).startsWith('semantic.terminal.'))) {
        throw new Error(`ANSI roles belong in adapters/ansi.json, not Neovim highlights: ${name}`);
      }
    }
    const visited = new Set([name]);
    let next = groups[name].link;
    while (next) {
      if (!Object.hasOwn(groups, next)) throw new Error(`Unresolved Neovim highlight link: ${next}`);
      if (visited.has(next)) throw new Error(`Neovim highlight link cycle: ${name}`);
      visited.add(next);
      next = groups[next].link;
    }
  }
  return Object.fromEntries(Object.keys(groups).sort().map(name => [name,
    Object.fromEntries(Object.entries(groups[name]).map(([key, value]) => [
      key, ['fg', 'bg', 'sp'].includes(key) ? portableColor(value, model) : value
    ]))
  ]));
}

export function renderNeovim(mapping, ansi, model) {
  const groups = neovimHighlights(mapping, model);
  const terminal = renderAnsi(ansi, model);
  const lines = [
    '-- Generated by npm run generate; edit tokens/ and adapters/, not this file.',
    'vim.o.background = "dark"',
    'vim.cmd("highlight clear")',
    'if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end',
    `vim.g.colors_name = ${JSON.stringify(model.variant.id)}`,
    '',
    'local highlights = {'
  ];
  for (const [name, style] of Object.entries(groups)) {
    const entries = Object.keys(style).sort().map(key => `${key} = ${JSON.stringify(style[key])}`);
    lines.push(`  [${JSON.stringify(name)}] = { ${entries.join(', ')} },`);
  }
  lines.push('}', 'for name, style in pairs(highlights) do', '  vim.api.nvim_set_hl(0, name, style)', 'end', '');
  ansiSlots.forEach((slot, index) => lines.push(`vim.g.terminal_color_${index} = ${JSON.stringify(terminal[slot])}`));
  lines.push('');
  return lines.join('\n');
}

export function buildPorts(sources = loadSources(), mappings = loadPortMappings()) {
  const models = compileSources(sources);
  const outputs = new Map();
  for (const key of portableVariants) {
    const model = models.find(item => item.variant.key === key);
    if (!model) throw new Error(`Missing portable variant: ${key}`);
    outputs.set(`windows-terminal/${model.variant.id}.json`,
      stableJson(renderWindowsTerminal(mappings['windows-terminal'], mappings.ansi, model)));
    outputs.set(`neovim/colors/${model.variant.id}.lua`, renderNeovim(mappings.neovim, mappings.ansi, model));
    outputs.set(`oh-my-posh/${model.variant.id}.omp.json`, stableJson(renderOhMyPosh(mappings['oh-my-posh'], model)));
  }
  return outputs;
}
